### ISSUE TITLE
项目一中有个小bug

### ISSUE THREAD

**Issue by elderdog** [jiangyongjian/IrregularTabBar#1]
项目一中屏幕旋转会使tabbar错位，而且如果根据屏幕方向重新设置tabbarframe的话，tabbar按钮有时会劫持到页面的点击事件，希望作者能看一下

**Comment by jiangyongjian** [comment]
一般iOS很少主界面有屏幕需要旋转的吧。只能说你项目。。。。当然，我是没有考虑屏幕旋转问题，我觉得屏幕旋转几乎可以忽略。加我qq453255376聊吧
